### ISSUE TITLE
The first sample script seems to run indefinitely.

### ISSUE THREAD

**Issue by DJuego** [NicolasHug/Surprise#139] opened 2018-01-31 21:43 UTC
Hi! I am a newbie with Surprise.

I have installed Surprise (1.0.5) in WinPython (WinPython-64bit-3.6.3.0Qt5). I am in Windows 10 x64.
Apparently, the installation was flawless.
However when i test the first sample code:

```python
from surprise import SVD
from surprise import Dataset
from surprise.model_selection import cross_validate

# Load the movielens-100k dataset (download it if needed),
data = Dataset.load_builtin('ml-100k')

# We'll use the famous SVD algorithm.
algo = SVD()

# Run 5-fold cross-validation and print results
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)
```
**I 'never' get a result. The script seems to run indefinitely.**  Just in case I've waited more than two hours... I heard clearly the acceleration fan CPU noise... 
(The first time the database was downloaded without problems)

I have not problem with another samples. For instance;
```python

from surprise import SVD
from surprise import Dataset
from surprise import accuracy
from surprise.model_selection import train_test_split

# Load the movielens-100k dataset (download it if needed),
data = Dataset.load_builtin('ml-100k')

# sample random trainset and testset
# test set is made of 25% of the ratings.
trainset, testset = train_test_split(data, test_size=.25)

# We'll use the famous SVD algorithm.
algo = SVD()

# Train the algorithm on the trainset, and predict ratings for the testset
algo.fit(trainset)
predictions = algo.test(testset)

# Then compute RMSE
accuracy.rmse(predictions)

```
I get: 

RMSE: 0.9450

I think my problem is related with cross_validate.
I request confirmation that the sample script is working properly in 1.0.5. 
And Could you tell me in what configuration it has been tested successfully. Thanks!! And congrats for SurPRISE! 👍 

P.S: I doubt that the problem is in the setting (Winpython, Windows 10 x64, ...) I have worked with scikit_learn in the same setting. No problem. It is fair to admit that scikit_learn is preinstalled in Winpython.

**Comment by NicolasHug** [comment] 2018-02-01 09:24
Hi,

Thanks for reporting this issue. I confirm that the sample script works fine... one linux :)
Unfortunately I have no windows environement to test it.

If the other examples are running, that might be related to joblib (which is used for parallel computing. So maybe the different processes are not synchronizing well?). Could you  please try to run a GridSearchCV procedure (e.g. [this one](https://github.com/NicolasHug/Surprise/blob/master/examples/grid_search_usage.py))? GridSerchCV also uses joblib.

**Comment by DJuego** [comment] 2018-02-01 11:14
Thanks for your swift answer @NicolasHug !

Yes. Same problem with GridSearchCV . I have used the script you proposed.  
I waited half an hour before killing the process...

As an anecdote, I have tested a sample with the "scikit-learn GridSearchCV". ([this one](http://scikit-learn.org/stable/auto_examples/model_selection/plot_grid_search_digits.html)). The expected output was almost inmediate. 

Is it possible to disable parallel computing (joblib)?

Do you think i should create an issue in [Winpython ](https://github.com/winpython/winpython)and/or [joblib](https://github.com/joblib/joblib)?

Thanks!

DJuego

P.S: My CPU is Intel Core i7-4790K (2014)

**Comment by NicolasHug** [comment] 2018-02-02 07:07
Thanks for the feedback, so it definitely seems that it's related to joblib in some way. The scripts should run in a few seconds so you don't need to wait so long.

Yes you can disable parallel computing by setting `n_jobs` to 1 in `coss_validate`. Does that work?

>Do you think i should create an issue in Winpython and/or joblib?

Probably not for now. I'm not familiar with Winpython. Did you install susprise using pip, conda, something else?

**Comment by DJuego** [comment] 2018-02-02 17:49
Hi, @NicolasHug 
Your intuition seems correct. When i run:

```python
from surprise import SVD
from surprise import Dataset
from surprise.model_selection import cross_validate

# Load the movielens-100k dataset (download it if needed).
data = Dataset.load_builtin('ml-100k')

# Use the famous SVD algorithm.
algo = SVD()

# Run 5-fold cross-validation and print results.
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True, n_jobs=1)
```
I get (after twenty seconds approx.):

```
Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9396  0.9379  0.9294  0.9392  0.9345  0.9361  0.0038  
MAE (testset)     0.7400  0.7424  0.7328  0.7394  0.7359  0.7381  0.0034  
Fit time          3.69    3.72    3.71    3.72    3.69    3.71    0.01    
Test time         0.10    0.09    0.10    0.14    0.09    0.10    0.02 
```

Too, i get results with the GridSearchCV sample:

```python
"""
This module describes how to use the GridSearchCV() class for finding the best
parameter combination of a given algorithm.
"""

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from surprise import SVD
from surprise import Dataset
from surprise.model_selection import GridSearchCV

# Use movielens-100K
data = Dataset.load_builtin('ml-100k')

param_grid = {'n_epochs': [5, 10], 'lr_all': [0.002, 0.005],
              'reg_all': [0.4, 0.6]}
gs = GridSearchCV(SVD, param_grid, measures=['rmse', 'mae'], cv=3, n_jobs=1)

gs.fit(data)

# best RMSE score
print(gs.best_score['rmse'])

# combination of parameters that gave the best RMSE score
print(gs.best_params['rmse'])

# We can now use the algorithm that yields the best rmse:
algo = gs.best_estimator['rmse']
algo.fit(data.build_full_trainset())

import pandas as pd  # noqa
results_df = pd.DataFrame.from_dict(gs.cv_results)
```

The output i get is:

```
0.964118988902
{'n_epochs': 10, 'lr_all': 0.005, 'reg_all': 0.4}
```


**Did you install susprise using pip, conda, something else?**

Well. I am newbie in Python. I use a gui interface for installing packages ([the graphical WinPython Package Manager "WinPython Control Panel](https://github.com/winpython/winpython/wiki/WPPM)").
I hadn't had any trouble so far (e.g. scikit-learn)

I find the SurPRISE package [here](https://pypi.python.org/pypi/scikit-surprise).

However, I am going to try to use the standard PIP Python package manager. I'll keep you posted.

DJuego

**Comment by NicolasHug** [comment] 2018-02-02 18:04
Thanks for the feedback.

I don't personally use it but [anaconda](https://www.anaconda.com/download/) is popular among Windows users and apparently easy to use. There's a conda package for surprise so it should run well if you install it from there.

**Comment by DJuego** [comment] 2018-02-02 19:00
Thanks for your time, @NicolasHug.

Well. I have installed SurPRISE in a "fresh" WinPython with PIP. See [here](http://imgbox.com/CVnOh8Ae).

But the problem persist. See output [here](http://imgbox.com/i4x6wBpF). Again, the script freezes.

I am allergic to installers (:-P). WinPython is portable (not installation is required). Indeed, my experience with python has been very good. However i could test Anaconda with this problem in a Virtual Machine. 

DJuego

**Comment by NicolasHug** [comment] 2018-03-06 21:24
Coming back to you on this,

Are you still experimenting this problem? If so, I suspect it's related to WinPython (because Surprise works fine on windows with more classical Python setups), but honestly I wouldn't have time to investigate the issue as this is a bit of an edge-case. Do you mind if I close the issue?

**Comment by DJuego** [comment] 2018-03-06 21:44
Well, @NicolasHug.  During these days I have focused on other tasks. I must also admit that I am evaluating other recommendation systems playgrounds for my purposes (for instance,  [spotlight](https://github.com/maciejkula/spotlight),   [lightfm](https://github.com/lyst/lightfm), [pyreclab](https://github.com/gasevi/pyreclab) or [CaseRecommender](https://github.com/ArthurFortes/CaseRecommender)) Also, I suspect that content-based filtering is better suited to the specifications of my problem...

In any case, I will try to test it with anaconda. If it is work, i will create a issue in Winpython. Any case, I will try that you will be informed. :-)

**Comment by NicolasHug** [comment] 2018-03-06 21:47
Anaconda does work, see e.g. #142 . This is why I think the problem comes from your specific setup, not from surprise nor joblib. Just the combination of surprise + joblib + winpython.

**Comment by DJuego** [comment] 2018-03-07 00:15
In Winpython it works with n_jobs=-1   but that is already a known fact. :-)

I have test Anaconda in Windows 10 x64. I used: `conda install -c conda-forge scikit-surprise`
It does not work if you do not specify n_jobs,

 It works in Anaconda. with n_jobs=1 (as described in #142 ). But It is not working with n_jobs=-1 (?) or n_jobs=2.  is it normal?

**Comment by NicolasHug** [comment] 2018-03-07 08:04
OK so if it's still not working with conda, I'd say the issue comes from your part. What processor do you have?

Can you try this scikit-learn code:

    from sklearn import datasets, linear_model
    from sklearn.model_selection import cross_val_score
    diabetes = datasets.load_diabetes()
    X = diabetes.data[:150]
    y = diabetes.target[:150]
    lasso = linear_model.Lasso()
    print(cross_val_score(lasso, X, y, n_jobs=-1))

**Comment by DJuego** [comment] 2018-03-07 11:28
Hi again, @NicolasHug 
Really, I think that @joerngrahl  has the same problem in #142. He needs to use n_jobs=1 in that code. 
Same as me. True?

In any case i am testing in my **laptop** now . I attach the CPU specifications.

I have tested that code. Ten minutes. The noise of the fans increase. But no result.

I change n_jobs=-1 to n_jobs=1. The output is immediate.

` [0.33150734 0.08022311 0.03531764]`


![laptop cpu](https://user-images.githubusercontent.com/1956212/37090009-9738ff84-21fa-11e8-85a2-1a1b384f6aa4.png)

**Comment by NicolasHug** [comment] 2018-03-07 11:34
I think the problem in #142 was just the typo, not the joblib part.

Thanks for trying the code, so as this code is just pure scikit learn (and we can be pretty sure scikit learn runs perfectly on windows), the problem is on your side and it's somehow related to joblib, but not related to scikit learn nor surprise.

**Comment by kman0** [comment] 2018-03-17 00:44
@NicolasHug I might be wrong, but I beg to differ with your opinion here. 

There is a small but very severe implementation difference between scikit-learn and your implementation of cross evaluation functions. In scikit-learn, the cv function def, as seen [here](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/cross_validation.py) has n_jobs default value of 1. But in your implementation it is -1.

As a result, in windows environment, it tries to use all processors available instead of using only one. This results in a hung loop with error 

> ImportError: [joblib] Attempting to do parallel computing without protecting your import on a system that does not support forking. To use parallel-computing in a script, you must protect your main loop using "if __name__ == '__main__'". Please see the joblib documentation on Parallel for more information

Correct implementation would be to set n_jobs=1 at all places which use parallel processing. This will require all code that use this library to force set n_jobs=1 to run with multiple cores.

I will be happy to post a pull request if you think this is a viable solution.

> I think the problem in #142 was just the typo, not the joblib part.

> Thanks for trying the code, so as this code is just pure scikit learn (and we can be pretty sure scikit learn runs perfectly on windows), the problem is on your side and it's somehow related to joblib, but not related to scikit learn nor surprise.

**Comment by kman0** [comment] 2018-03-17 00:46
@NicolasHug One other point to note is the fact that any windows user, who want to use this library will never be able to do so unless they read the issues on github and set n_jobs=1. :(

**Comment by NicolasHug** [comment] 2018-03-17 08:47
Yeah I agree with you, there's something fishy there.

I thought #142 was just the typo but I read the comment too fast and thought he'd been able to set `n_jobs=-1`, but no.

My plan was to ask scikit-learn team if there was a particular reason they would default `n_jobs` to `1` instead of `-1`. If their answer is "it doesn't work on widows unless you use the `__main__` trick" then we should definitely default it to `1` as well.

But maybe you can help me sort out this issue:
- Are you running windows?
- Do you experience the same problems?
- Can you work around it by using the `if __name__=="__main__"` trick?

**Comment by kman0** [comment] 2018-03-19 02:24
> Are you running windows?

Yes, I am running on windows
> Do you experience the same problems?

Yes, when I run, the script runs infinitely. 
To be precise, multiprocess works differently in linux and windows. In case of linux, the process is forked, i.e., the execution of code above the point of parallelization happens only once. 
But in case of windows, afaik, the sub process spawns and code executes from line one. We need to control what lines of code is executed in subprocess i.e., do the forking manually in code. That is what the __main__ check does.
When no check is made, the subprocess spawns ***recursively*** and that is what I see when I use it in windows. joblib has a check to avoid such a case and they throw an exception and give directions to control the flow of the code.
> Can you work around it by using the if __name__=="__main__" trick?

No, I doubt if that is doable at all in the case of windows. see [here ](http://pythonhosted.org/joblib/parallel.html#common-usage)

Also, I looked up the defaults in joblib. They, themselves have set the n_jobs=1. 
```
        if n_jobs is None:
            # No specific context override and no specific value request:
            # default to 1.
            n_jobs = 1
```

**Closed** 2018-04-02 12:38 UTC

**Comment by gopal-gcek** [comment] 2020-01-21 10:29
Can any one help me how to handel  this error 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-6e6a3439743c> in <module>()
      6               'reg_all': [0.4, 0.6]}
      7 # Cross-validation using grid search
----> 8 grid_search = GridSearchCV(SVD, param_grid, measures=['rmse', 'mae'], cv=3, n_jobs=1)
      9 # Find the best parameters on the data set
     10 data = Dataset.load_builtin('ml-100k')

TypeError: __init__() got an unexpected keyword argument 'measures'
