### ISSUE TITLE
some problem in the similarities.pyx

### ISSUE THREAD

**Issue by bluoy** [NicolasHug/Surprise#217] opened 2018-10-18 06:43 UTC
we found a bug in No. 92 line in the  similarities.pyx:
----------------------------------------------------------------------------------
                #denum = np.sqrt(sqi[xi, xj] * sqj[xi, xj])
                denum = np.sqrt(sqi[xi, xi] * sqj[xj, xj])        #bugfixed! 
--------------------------------------------------------------------------
please correct it.

**Comment by NicolasHug** [comment] 2018-10-18 11:38
This code is correct with regards to the way we define [cosine similarity](https://surprise.readthedocs.io/en/stable/similarities.html#surprise.similarities.cosine)

**Comment by NicolasHug** [comment] 2018-10-18 15:11
(as far as I can tell)

But of course feel free to correct me if I'm wrong

**Comment by bluoy** [comment] 2018-10-19 02:09
thans for your quickly reply.

we compare the result of scipy.spatial.distance.cdist() function. it's different.
Y = cdist(XA, XB, 'cosine') 

but cdist()'s result is more matched.

**Comment by NicolasHug** [comment] 2018-10-19 11:49
The problem is that cosine sim isn't strictly defined for rating vectors.

- 1 You can either choose the compare the entire vectors, filling the missing entries with zero

- 2 You can compare vectors of different sizes by not filling the missing entries.

- 3  Or you can compare vectors of the same size, not filling entries, by comparing only the vectors on their common ratings.

Surprise does 1, and using the formula from scipy will give you 1 or 2 depending on if you consider the unknown ratings.

There is no "correct" or wrong way of doing it, those are just different versions.

**Comment by bluoy** [comment] 2018-10-22 06:34
Let's see an example.

sample data:
	user:A,B,C,D	[0,1,2,3]
	item:a,b,c,d,e	[0,1,2,3,4]

		a	b	c	d	e
	A	1	1	0	1	0
	B	1	0	1	0	0
	C	0	0	1	0	1
	D	0	1	1	0	1
	
first, we can easily find the C and D is more similar.

with surprise.cosine():
n_x=4
yr={0:[(0,1),(1,1)],1:[(0,1),(3,1)],2:[(1,1),(2,1),(3,1)],3:[(0,1)],4:[(2,1),(3,1)]}
min_support=1
cosine(n_x, yr, min_support)'s result is:

		A	B	C	D
	A	1.00	1.00	0.00	1.00
	B	1.00	1.00	1.00	1.00
	C	0.00	1.00	1.00	1.00
	D	1.00	1.00	1.00	1.00

cdist()'s result is:

		A	B	C	D
	A	1.00	0.41	0.00	0.33
	B	0.41	1.00	0.50	0.41
	C	0.00	0.50	1.00	0.82
	D	0.33	0.41	0.82	1.00

so we think cdist()'s result is more matched.
Is this correct?

**Comment by NicolasHug** [comment] 2018-10-22 13:14
Like I said 

>There is no "correct" or wrong way of doing it, those are just different versions.

If using cdist makes more sense for your application (you seem to have binary ratings, so indeed it could make sense) then go for it.

I'll close the issue as this is not a bug in surprise implementation. Surprise computes the cosine similarity  exactly as it claims it does.

**Closed by NicolasHug** 2018-10-22 13:14 UTC

**Comment by bluoy** [comment] 2018-10-22 17:03
Of couse you can close it.

I just want to say: if we change the surprise code, we can get the same result with cdist().



发自我的小米手机在 Nicolas Hug <notifications@github.com>，2018年10月22日 21:14写道：Like I said

There is no "correct" or wrong way of doing it, those are just different versions.

If using cdist makes more sense for your application (you seem to have binary ratings, so indeed it could make sense) then go for it.
I'll close the issue as this is not a bug in surprise implementation. Surprise computes the cosine similarity  exactly as it claims it does.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NicolasHug/Surprise","title":"NicolasHug/Surprise","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/NicolasHug/Surprise"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NicolasHug in #217: Like I said \r\n\r\n\u003eThere is no \"correct\" or wrong way of doing it, those are just different versions.\r\n\r\nIf using cdist makes more sense for your application (you seem to have binary ratings, so indeed it could make sense) then go for it.\r\n\r\nI'll close the issue as this is not a bug in surprise implementation. Surprise computes the cosine similarity  exactly as it claims it does."}],"action":{"name":"View Issue","url":"https://github.com/NicolasHug/Surprise/issues/217#issuecomment-431832078"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/NicolasHug/Surprise/issues/217#issuecomment-431832078",
"url": "https://github.com/NicolasHug/Surprise/issues/217#issuecomment-431832078",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [NicolasHug/Surprise] some problem in the similarities.pyx (#217)",
"sections": [
{
"text": "",
"activityTitle": "**Nicolas Hug**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@NicolasHug",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"NicolasHug/Surprise\",\n\"issueId\": 217,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/NicolasHug/Surprise/issues/217#issuecomment-431832078"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 397611294\n}"
}
],
"themeColor": "26292E"
}
]
---------------------------------------------------------------------------------------------------Confidentiality Notice: The information contained in this e-mail and any accompanying attachment(s) is intended only for the use of the intended recipient and may be confidential and/or privileged of Neusoft Corporation, its subsidiaries and/or its affiliates. If any reader of this communication is not the intended recipient, unauthorized use, forwarding, printing,  storing, disclosure or copying is strictly prohibited, and may be unlawful.If you have received this communication in error,please immediately notify the sender by return e-mail, and delete the original message and all copies from your system. Thank you. ---------------------------------------------------------------------------------------------------
