### ISSUE TITLE
cross_validate verbose=False does not suppress output

### ISSUE THREAD

**Issue by kand** [NicolasHug/Surprise#158] opened 2018-03-29 03:00 UTC
#### Description
When using `cross_validate`, no matter the value for the `verbose` parameter, strings describing the current step are printed.

#### Steps/Code to Reproduce

Given the following script:

```
from surprise.prediction_algorithms.knns import KNNWithMeans
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise.model_selection.split import KFold

random_state = 42

data = Dataset.load_builtin('ml-100k')

user_knn_opts = {
    'name': 'pearson',
    'user_based': True
}
user_knn = KNNWithMeans(sim_options=user_knn_opts)

cross_validate(
    user_knn,
    data,
    measures=['RMSE'],
    cv=KFold(n_splits=5, random_state=random_state),
    verbose=False,
)
```

The following is printed:

```
Computing the pearson similarity matrix...
Computing the pearson similarity matrix...
Computing the pearson similarity matrix...
Computing the pearson similarity matrix...
Done computing similarity matrix.
Done computing similarity matrix.
Done computing similarity matrix.
Done computing similarity matrix.
Computing the pearson similarity matrix...
Done computing similarity matrix.
```

Which I believe is coming from this [code location in `AlgoBase`](https://github.com/NicolasHug/Surprise/blob/6c5ba103ab1d628f4aa19ed8ec88b0abaee1c28d/surprise/prediction_algorithms/algo_base.py#L290-L293). No `verbose` parameter wraps these calls, so their output cannot be suppressed.

#### Expected Results

I would expect that no output is produced when running `cross_validate` with `verbose=False` or when no `verbose` parameter is supplied; the documentation states that `verbose` defaults to `False`.

#### Actual Results

Output of intermediate steps for `cross_validate` are printed.

#### Versions

```
Darwin-17.4.0-x86_64-i386-64bit
Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:05:31) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
surprise 1.0.5
```

**Comment by NicolasHug** [comment] 2018-03-29 08:54
You're absolutely correct with your obserations.

This is a duplicate of #145 and is currently addressed in a PR.

**Closed** 2018-04-02 12:58 UTC
