### ISSUE TITLE
Read The Docs link to Github broken

### ISSUE THREAD

**Issue by perwagner** [NicolasHug/Surprise#111] opened 2017-11-19 14:06 UTC
#### Description
The link on the Read The Docs site to the Github repo is not working (leading to a 404 page). The link on RTD is "https://github.com/NicolasHug/Surprise/blob/c95e42a65a333d2f894c7f97d1401cd5860cffce/doc/source/getting_started.rst". 

#### Steps/Code to Reproduce
Go to "http://surprise.readthedocs.io/en/stable/index.html". Click the GitHub link in the top right corner.

#### Expected Results
Be taken to "https://github.com/NicolasHug/Surprise"

#### Actual Results
Taken to a Github 404 page.

**Comment by NicolasHug** [comment] 2017-11-19 15:15
Thanks a lot for reporting this.

After a bit (a lot actually) of bug tracking, this is caused by `c95e42a65a333d2f894c7f97d1401cd5860cffce` being a tag hash, not a commit tag.

This kind of issue has already been raised in
[rtfd/readthedocs.org#1820](https://github.com/rtfd/readthedocs.org/issues/1820), but there does not seem to be a fix for now?

**Comment by perwagner** [comment] 2017-11-19 15:32
You are right. I couldn't find anyone who had a solution for this particular case. Maybe a github or RTD update at some point will solve it.

**Comment by NicolasHug** [comment] 2017-11-19 15:36
I guess the current workaround is to switch to `latest` or `1.0.4` version on the docs, and follow the link from here, as there doesn't seem to be any problem with these versions.

**Comment by NicolasHug** [comment] 2018-01-11 09:25
I wouldn't know why but it looks like this is now fixed with the new release 1.0.5 :)

**Closed by NicolasHug** 2018-01-11 09:25 UTC
