### ISSUE TITLE
GridSearchCV - random_state

### ISSUE THREAD

**Issue by PoeteMaudit** [NicolasHug/Surprise#212] opened 2018-10-10 16:30 UTC
#### Description

I have the impression that there is no way to specify a `random_state` at the prediction algorithm you use at `GridSearchCV`.

For example, when I try to do this: 
```
parameters_grid = {'n_factors': list(range(5, 11, 5))}
from surprise.model_selection import GridSearchCV
from surprise.prediction_algorithms import SVD
model = SVD(random_state=0)
model_grid = GridSearchCV(algo_class=model, param_grid=parameters_grid, cv=2)
model_grid.fit(train_set)
```

then I get the following error at the line `model_grid.fit(train_set)`:
```
for params, (trainset, testset) in product(self.param_combinations,
TypeError: 'SVD' object is not callable
```
while if do it like this:
```
parameters_grid = {'n_factors': list(range(5, 11, 5))}
from surprise.model_selection import GridSearchCV
from surprise.prediction_algorithms import SVD
model_grid = GridSearchCV(algo_class=SVD, param_grid=parameters_grid, cv=2)
model_grid.fit(train_set)
```

then the whole thing is running fine.

How can I specify a `random_state` at the prediction algorithm I use at `GridSearchCV `(than perhaps doing it by myself with `numpy.random.seed`)?

**Comment by NicolasHug** [comment] 2018-10-10 16:45
Yeah, for some reason (very probably under-thinking from my part), GridSearchCV accepts only classes, not estimator instances like in scikit learn. That's not great and it would be a nice addition.

That being said, there's a workaround: you can just have your grid like this:

`parameters_grid = {'n_factors': list(range(5, 11, 5)),
                    'random_state'=[2]}`

**Comment by PoeteMaudit** [comment] 2018-10-10 16:57
Thank you for your instant reply.

It is in general good to have some notes even at the docs which clarify these things.
Otherwise, we have to guess or bother you here every time we find something like that.

Moreover, first of all, I guess you mean: 
`parameters_grid = {'n_factors': list(range(5, 11, 5)), 'random_state': [2]}`
with `'random_state':` not `'random_state'=`?

Secondly, I did specify the `random_state` with `'random_state':[0]`
but every time I run I got different `RMSE `results (0.8753, 0.8786, 0.8806 etc) with `cv_results`.
Therefore, what is it going here?

**Comment by NicolasHug** [comment] 2018-10-10 17:20
That's probably because the grid search is evaluated across different folds each time. You can explicitly set the folds with:

`GridSearchCV(SVD, param_grid, measures=['rmse'], cv=KFold(3, random_state=2))`


>with 'random_state': not 'random_state'=?

yes

>It is in general good to have some notes even at the docs which clarify these things.
Otherwise, we have to guess or bother you here every time we find something like that.

100% agree, feel free to submit a PR

**Comment by PoeteMaudit** [comment] 2018-10-10 17:34
Thanks, that's a good point about `random_state `at the cross-validation iterator.

**Comment by NicolasHug** [comment] 2018-10-10 17:37
To be honest I would have expected that if you pass an `int` to `cv` you get the same folds every time, but as far as I understand scikit-learn code the splits would be different there as well.

**Comment by NicolasHug** [comment] 2018-10-10 18:09
I've opened #213 which is more general so I'll close this one OK?

**Closed by NicolasHug** 2018-10-10 18:09 UTC

**Comment by resurrexi** [comment] 2019-03-14 16:49
I tried passing an instance of KFold with a specified `random_state` to my GridSearchCV instance, but the folds seem to be still generated randomly. I also tested whether scikit-learn's GridSearchCV implementation was generating random folds after each kernel/seed reset, but it wasn't the case. The results were consistent.

I'm going to take a look at the source code tomorrow and find the root cause of this confounding behavior.

**Comment by resurrexi** [comment] 2019-03-15 09:21
I was able to find the culprit for the varying results. It happens when the grid search is parallelized (when n_jobs > 1). Joblib provides 3 backends, and by default it uses loky when n_jobs > 1. This causes the subprocesses to use some random seed instead of the ones set by `random.seed` and `np.random.seed`, thus breaking reproducibility. As an example, I created a function to demonstrate:

```python
def generate():
    return (np.random.randn(1), random.random())
```

Below is the output of the result even after resetting the seed.

```python
>>> random.seed(123)
>>> np.random.seed(123)
>>> Parallel(n_jobs=2)(delayed(generate)() for i in range(3))
[(array([0.55422086]), 0.601322995632844), (array([0.69842927]), 0.9910148484975828), (array([1.52733832]), 0.6780137700740274)]
>>> random.seed(123)
>>> np.random.seed(123)
>>> Parallel(n_jobs=2)(delayed(generate)() for i in range(3))
[(array([-0.16017005]), 0.8610927673314497), (array([0.36140858]), 0.8878536818848503), (array([-1.58392452]), 0.244057551706355)]
```

If I set n_jobs=1, then joblib will use the sequential backend and will produce consistent results:

```python
>>> random.seed(123)
>>> np.random.seed(123)
>>> Parallel(n_jobs=1)(delayed(generate)() for i in range(3))
[(array([-1.0856306]), 0.052363598850944326), (array([0.99734545]), 0.08718667752263232), (array([0.2829785]), 0.4072417636703983)]
>>> random.seed(123)
>>> np.random.seed(123)
>>> Parallel(n_jobs=1)(delayed(generate)() for i in range(3))
[(array([-1.0856306]), 0.052363598850944326), (array([0.99734545]), 0.08718667752263232), (array([0.2829785]), 0.4072417636703983)]
```

On a side note, I also tried joblib's threading backend, which also produced consistent results, but considering that the algorithms are more CPU heavy, threading is not the way to go.

```python
>>> random.seed(123)
>>> np.random.seed(123)
>>> Parallel(n_jobs=2, prefer="threads")(delayed(generate)() for i in range(3))
[(array([-1.0856306]), 0.052363598850944326), (array([0.99734545]), 0.08718667752263232), (array([0.2829785]), 0.4072417636703983)]
>>> random.seed(123)
>>> np.random.seed(123)
>>> Parallel(n_jobs=2, prefer="threads")(delayed(generate)() for i in range(3))
[(array([-1.0856306]), 0.052363598850944326), (array([0.99734545]), 0.08718667752263232), (array([0.2829785]), 0.4072417636703983)]
```

Based on the link provided [here](https://joblib.readthedocs.io/en/latest/auto_examples/parallel_random_state.html#fixing-the-random-state-to-obtain-deterministic-results), the authors propose passing the seed to the function (or the algo class in this case) to produce deterministic results.

**Comment by NicolasHug** [comment] 2019-03-15 11:04
Are you sure you're passing the random_state into your estimator?

Like in https://github.com/NicolasHug/Surprise/issues/212#issuecomment-428645591 ?

**Comment by NicolasHug** [comment] 2019-03-18 11:31
@resurrexi can you (dis)confirm that you get reproducible results by setting the random state of both the estimator and the cv object?

**Comment by resurrexi** [comment] 2019-03-18 14:54
@NicolasHug Apologies for the delay.

Passing the `random_state` for the grid search to tune on worked, but I just find it odd having to set it in the `param_grid`.

As for the `cv` argument, the results were consistent regardless of whether an integer or a KFold instance was passed.

**Comment by NicolasHug** [comment] 2019-03-18 14:56
Thanks for the feedback.

> I just find it odd having to set it in the param_grid

Yes I agree, Ideally we should just use an instance of the algorithm that was passed the `random_state`. This requires passing instances to `GridSearchCV` instead of classes, which is why I opened #213

**Comment by Prasang-Biyani** [comment] 2023-02-18 10:27
I tried passing the `random_state` in the estimator, it worked like a charm.
