### ISSUE TITLE
Bug: current kNN implementation gives wrong prediction for an item user has already rated

### ISSUE THREAD

**Issue by ODemidenko** [NicolasHug/Surprise#134] opened 2018-01-29 13:45 UTC
as kNN currently always search for K closest neighbors among those who rated an item, and this set of users is not fixed - it will retrieve the rated user (item) itself, among those closest, as it has the highest similairy to itself.
Thus, current prediction will tend to always being better, than it actually is, for new items. I didn't check it, but it probablyalso compromises metrics for kNN, giving overly good results

**Comment by NicolasHug** [comment] 2018-01-29 14:27
That's true.
And that's (still) not a bug.
It's perfectly normal: if you disclose some data a prediction algorithm, there is no reason the algorithm should not use this data. It's up to you to decide which data you want the algorithm to use.

All algorithms overfit  when they're tested on some training data, that's why you should always keep the two sets disjoint.

**Comment by ODemidenko** [comment] 2018-01-29 20:21
I expect that kNN will always make predictions based on k neighbors and not on the current user (or item) itself, because this fails me when I try to compare predictions with actual values.

**Comment by NicolasHug** [comment] 2018-01-29 21:06
That's a fair point.
But consider the limit case of using 1-NN (in a classification setting, not in recommendation).
The 1-NN of a training instance **is** this very training instance. So you'd expect the prediction for this instance to be the correct class, not the class of the next closest instance (the 2-NN in this case).

Basically:
- strictly speaking, x belongs to k-NN(x).
- as we never test a prediction algorithm on a training instance (unless for particular cases like computing training error), we can never use x as a predictor precisely because it's not in the training set. So in practice, even if x is a neighbor, we can't use it to make a prediction.

**Comment by ODemidenko** [comment] 2018-01-29 21:16
I didn't understand your point. And I believe that x is not in kNN(x).
One of the way to use prediction for an item itself in practice - is to demonstrate to the user quality of the recommendations engine, by comparing algorithm's predictions to their true ratings. Current behaviour will do this incorrectly and unexpectedly.

**Comment by NicolasHug** [comment] 2018-01-29 21:21
>One of the way to use prediction for an item itself in practice - is to demonstrate to the user quality of the recommendations engine, by comparing algorithm's predictions to their true ratings.

Yes but **always** hiding the ground truth value. Sorry but that's very basic ML.
If you don't hide it, here is an algorithm that has a perfect score with your protocol, and that is totally worthless in practice:

    def estimate(u, i):                                                        
        if (u, i) in known_ratings:                                               
            return known_ratings[(u, i)]                                          
        else:                                                                     
            return 123456789

**Comment by ODemidenko** [comment] 2018-02-05 14:08
> Yes but always hiding the ground truth value. Sorry but that's very basic ML.

Regarding the ML approach - it is quite common to compare error on learning and validation curve, in order to understand whether the model suffers from bias or overfitting.  Although for recommender systems there isn't such a trade-off directly, but what I mean by the necessity to correctly predict on train data - is relevant for recommender systems, as it allows to get a clue on the generalization ability of the recommender system (i.e. how good it is in interpolating knowledge on new items). 
Finally, such comparison gives the theoretical limit of model performance, in case we have too little ratings to allow for a cross-validation.
These last two examples are probably somewhat imaginary, but they illustrate perspective on comparing this case to classical ML approaches.

So, even in case current prediction behaviour is done so intentionally - it makes sense to alter it, at least optionally, in order to allow a bunch of useful applications.

**Comment by NicolasHug** [comment] 2018-02-05 16:57
Basically what you want is to not use some training data, depending on the instance the algorithm will be tested on. 
                                                                               
That's a **complete anti-pattern**. For many algorithms (those that build a model, e.g. SVD), it's also impossible.
                                                                               
If an instance is in the training set, the algorithm should be able to use it. That's it, really.
                                                                               
Have you heard of the Leave-One-Out cross-validation strategy? I strongly believe that this is what you are actually trying to do here.
                                                                               
I'll close the issue if you don't mind, as this is really not a bug. The current behaviour is the correct one, and it won't change.

**Comment by ODemidenko** [comment] 2018-02-05 23:37
Nicolas, you almost convinced me by comparing to SVD case. Please, close the issue

**Closed** 2018-02-06 07:26 UTC
