### ISSUE TITLE
Top N recommendations for a specific user

### ISSUE THREAD

**Issue by neeravmakwana** [NicolasHug/Surprise#114] opened 2017-11-29 03:19 UTC
#### Description
Hi, how can I get top N recommendations for a specific user?

Should I use get_top_n or predict, and more importantly what parameters should I pass?

**Comment by NicolasHug** [comment] 2017-11-29 07:19
Hi,

It looks like you have missed the headline before submitting this issue:

>IMPORTANT PLEASE READ!!!
Before submitting an issue, make sure it hasn't already been addressed by
checking the past issues and the documentation (FAQ, getting started / advanced
usage guide, etc.). In order to let me help you more efficiently, please fill
the different fields below (Description, Steps to reproduce, etc.).
>
>Also, please keep in mind that I develop and maintain this software on my
**free time**. So please, before asking for help, show me that you have already
tried to solve your problem for more than 5 seconds. That would be greatly
appreciated!
>
>Thank you! :)


Feel free to come back to me.
Nicolas

**Closed by NicolasHug** 2017-11-29 07:19 UTC
