### ISSUE TITLE
Pip install error "Please install numpy>=1.11.2 first." should be handled differently

### ISSUE THREAD

**Issue by wontonst** [NicolasHug/Surprise#188] opened 2018-06-27 22:43 UTC
#### Description

I don't have a solution in mind yet but this error you get is kinda agitating for people who use surprise and have a CI pipeline. It forces us to do a manual install of numpy first, then the requirements, or do all the requirements, then addon surprise. There's definitely a better way to handle building the exts

```
(testenv) Roys-MacBook-Pro:Surprise royzheng$ pip install --no-cache scikit-surprise
Collecting scikit-surprise
  Downloading https://files.pythonhosted.org/packages/4d/fc/cd4210b247d1dca421c25994740cbbf03c5e980e31881f10eaddf45fdab0/scikit-surprise-1.0.6.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 16.2MB/s
    Complete output from command python setup.py egg_info:
    Please install numpy>=1.11.2 first.
```

#### Steps/Code to Reproduce

See above

#### Expected Results
Installs the install_requires correctly and then installs surprise

#### Actual Results
Errors out

#### Versions
surprise
1.0.6
pip 10.0.1
py2.7

**Comment by NicolasHug** [comment] 2018-06-28 01:13
Closing, duplicate of #187

**Closed by NicolasHug** 2018-06-28 01:13 UTC
