### ISSUE TITLE
Values differences between KNNWithMeans methods and manual computation

### ISSUE THREAD

**Issue by TamTSE2301** [NicolasHug/Surprise#226] opened 2018-11-09 10:10 UTC
Hi,

Right now there is a mismatch from ‘Surprise’ library results to our manual computation and we are trying to figure out the reason. **Could you suggest the quickest way for us to access similarity matrix in Surprise library?**

Please find attached file the dataset I’m using and the codes for manual computation. Also, kindly note that:
- We are relying on your **KNNWithMeans** formula and the **pearsonr** in scipy.stats.pearsonr.
- We adjust the alogrithm a little bit by adding a paramater min_s (taking into account of smilarity above a certain threshold). And in case < min_k, we would raise PredictionImpossible('Not enough neighbours').
[missingdata.xlsx](https://github.com/NicolasHug/Surprise/files/2565396/missingdata.xlsx)
[predicted.xlsx](https://github.com/NicolasHug/Surprise/files/2565397/predicted.xlsx)

**Code for adjusted KNNWithMeans**

```
#Adjusted KKWithMeans
#Adjusted KNN With Means

"""
 The Adjusted_KNNWithMeans is originally based on KNNWithMeans with one adjustment:
     - We set up another parameter call 'min_s' which is the similarity threshold.
     - In other words, we only consider similarity > min_s
     - The default value for min_s would be 0.5
     - Other arguments (k(int),min_k(int),sim_options(dict),verbose(bool)), are 
       the same as KNNWithMeans
"""

class Adjusted_KNNWithMeans(SymmetricAlgo):

    def __init__(self, k=40, min_k=1, min_s=0.5, sim_options={}, verbose=True, **kwargs):

        SymmetricAlgo.__init__(self, sim_options=sim_options,
                               verbose=verbose, **kwargs)

        self.k = k
        self.min_k = min_k
        self.min_s = min_s


    def fit(self, trainset):

        SymmetricAlgo.fit(self, trainset)
        self.sim = self.compute_similarities()

        self.means = np.zeros(self.n_x)
        for x, ratings in iteritems(self.xr):
            self.means[x] = np.mean([r for (_, r) in ratings])

        return self

    def estimate(self, u, i):

        if not (self.trainset.knows_user(u) and self.trainset.knows_item(i)):
            raise PredictionImpossible('User and/or item is unkown.')
        
        x, y = self.switch(u, i)

        neighbors = [(x2, self.sim[x, x2], r) for (x2, r) in self.yr[y]]
 
       
        """      
        #Adjustment compared to original KNNWithMeans:

        """
        #self.sim[self.sim < self.min_s] = 0
        for i in range(0,len(neighbors)): 
            (n,sim,r)=neighbors[i]
            if sim < self.min_s:
                neighbors[i]= (n,np.NaN,r)
  
        """      
        #Below is the same as the origonal KNNWithMeans:

        """      
        
        k_neighbors = heapq.nlargest(self.k, neighbors, key=lambda t: t[1])

        est = self.means[x]

        # compute weighted average
        sum_sim = sum_ratings = actual_k = 0
        for (nb, sim, r) in k_neighbors:
            if sim > 0:
                sum_sim += sim
                sum_ratings += sim * (r - self.means[nb])
                actual_k += 1

        if actual_k < self.min_k:
            raise PredictionImpossible('Not enough neighbours')


        try:
            est += sum_ratings / sum_sim
        except ZeroDivisionError:
            pass  # return mean

        details = {'actual_k': actual_k}
        return est, details
```

Thank you in advance.

**Comment by NicolasHug** [comment] 2018-11-09 12:50
>Could you suggest the quickest way for us to access similarity matrix in Surprise library?

Use the `sim` attribute of the algorithm

>Right now there is a mismatch from ‘Surprise’ library results to our manual computation

What is the mismatch? Is it between `scipy.pearsonr` and the computed similarity values in surprise? Then it's completely independent of the prediction algorithm (KNNWithMeans).

Please provide a [self-contained example code](https://stackoverflow.com/help/mcve),  example so I can reproduce the issue and the mismatch.

>predicted.xlsx

Sorry, can't open xlsx files.

Also, this seems to be a duplicate of #224

**Comment by TamTSE2301** [comment] 2018-11-09 13:01
Hi,

The difference here is RMSE. This is my code. I dont think it's the same with #224 as I have fix the min_s (threshold of sim to be 0.1 at the beginning.

I don't know yet the reason for this difference. That's why I want to start from the similarity matrix.

I attached again the excel file. if you could not open it, i could send you by email. Note: predicted.xlsx is the actual value of NA values in missingdata.xlsx
[predicted.xlsx](https://github.com/NicolasHug/Surprise/files/2565917/predicted.xlsx)
[missingdata.xlsx](https://github.com/NicolasHug/Surprise/files/2565918/missingdata.xlsx)



```
#Libraires used:
import pandas as pd
import numpy as np
#This is a random dataset that needs predictions
data = pd.ExcelFile('missingdata.xlsx').parse('data')
data.head(10)

#List of NA (Values need to be predicted)
data['User']=data.index
NA = pd.melt(data,id_vars='User',value_vars=data.columns.drop('User').tolist())
data = data.drop('User',axis=1)

NA = NA[pd.isnull(NA['value'])]
NA.columns = ['User','Item','Value']

#This is the actual values for NA values
actual = pd.ExcelFile('predicted.xlsx').parse('data')
actual['User']=actual.index
actual = pd.melt(actual,id_vars='User',value_vars=data.columns.tolist()).dropna()
actual.columns = ['User','Item','Actual values']

#Some inportant parameters:
neighbor_size = 10 #number of neighbors. OR k (int) _ SURPRISE LIBRARY
min_similarity = 0.1
usable_neighbors = 2 #min number of neighbors used for prediction 
minSimSupport = 2 # or min_support (Surprise vocabulary)

from scipy.stats.stats import pearsonr

#We select Person similarity
def pearson_sim(v1, v2, minSimSupport=None):
    indexList = (v1[(-pd.isnull(v1)) & (-pd.isnull(v2))]).index
    if len(indexList) == 0 or (minSimSupport is not None and len(indexList) < minSimSupport):
        sim = 0
    else:
        sim, pvalue = pearsonr(v1[indexList], v2[indexList])
    return sim, len(indexList)

#Matrix of pearson similarities
sim_df = pd.DataFrame(np.zeros(shape=(10,10)),index=data.index,columns = data.index)

for i in range(10):
    for j in range(10):
        if i == j:
            sim_df.iloc[i,j] = np.NaN
        else:
            sim_per =  pearson_sim(data.iloc[i,],data.iloc[j,],2)[0]
            sim_df.iloc[i,j] = sim_per
            
                
print(sim_df)

#Filter sim > 0.1
neighbour_df = sim_df[sim_df >= min_similarity].fillna(0)
print(neighbour_df)

#The mean of all ratings given by each user
mean_user = data.mean(axis=1)
mean_user

imputation = pd.DataFrame(columns=['Predicted','Item','User'])
for i in range(10):
    
    #We apply the KNNwithMeans
    #The formula: https://surprise.readthedocs.io/en/stable/knn_inspired.html
    
    #'''The nominator'''
    #sum of sim(u,v)*(r_vi - mu_v)
    user = neighbour_df.iloc[i]
    user = user.drop(user.index[i]) #drop itself
    ar = pd.Series(user).sort_values(ascending=False)[:neighbor_size]
    neighbours = ar.keys()
    weights = ar.values
    #List of items corresponding to User i that needs to be predicted
    list_i  = pd.Series(NA.loc[NA['User']==neighbour_df.index[i],'Item'])
    
    #Ref: Values of neughbours that are used to predict User i
    ref = data.loc[pd.IndexSlice[neighbours],list_i].fillna(0)
    user_id = pd.DataFrame(neighbour_df.iloc[i]).columns
    u_id = np.logical_not(ref.index.isin(user_id)) #remove user itself
    ref = ref[u_id]
    
     #Check the condition of usable neighbours
    check = np.count_nonzero(ref,axis=0)
    check = (check >=usable_neighbors)*1
    check = check.astype('float')
    check[check == 0] = np.NaN
    

    #Mark the coordoniates that has value # 0
    weight_i = (ref/ref).fillna(0)

    #Caculate: (r_vi - mu_v)
    t = mean_user
    t = t.reindex(index=ref.index)

    for m in range(len(ref.columns)):
        ref.iloc[:,m] = ref.iloc[:,m] - t 
    
    ref = ref.multiply(weight_i) #ignore coordinates that has value = 0

    #Calculate SUM of sim(u,v)*(r_vi - mu_v)
    pred_nom = pd.DataFrame(np.matmul(weights,ref)).transpose()
    pred_nom.columns = ref.columns

    
    #'''The denominator'''
    pred_denom = pd.DataFrame(np.matmul(weights,weight_i)).transpose()
    pred_denom.columns = ref.columns
    
    #'''Final prediction'''
    u_target = mean_user.iloc[i]
    pred = pred_nom.div(pred_denom.iloc[0], axis=1)
    pred = pred.add(u_target)
    pred = pred.multiply(check) #to remove the case based on less than the number of usuable neighbours
    

    #Transform the dataset to have the same format as dataframe ('Imputation')
    pred.columns = list_i
    pred = pred.transpose()
    pred.columns = ['Predicted']
    pred['Item'] = pred.index
    pred['User'] = [neighbour_df.index[i]]*len(list_i)
    
    #Concatinate with imputation
    imputation = pd.concat([imputation,pred])

imputation = imputation.fillna(0)
imputation = imputation[imputation.Predicted != 0] #Values == 0 means could not predicted
#Crosscheck:
consol = pd.merge(actual,imputation,how='inner', left_on=['User','Item'], right_on = ['User','Item'])

#Check
absolute_error_df = (consol['Actual values'] - consol['Predicted']).abs()
#Mean absolute error:
print("MAE " + str(absolute_error_df.mean()))
#Root mean squared of error
MSE = (absolute_error_df ** 2).mean()
RMSE=np.sqrt(MSE)
print("RMSE " + str(RMSE))
```

**Comment by NicolasHug** [comment] 2018-11-09 13:16
`indexList = (v1[(-pd.isnull(v1)) & (-pd.isnull(v2))]).index`

It looks like you're not computing the pearson similarity on the common ratings only, so you're definitely get different results. Please take a look at the pearson similarity computation in the docs of surprise.

(it should be `~` instead of `-` BTW but that's unrelated.)


Sorry but it's very hard for me to help here since you don't have a clear idea yourself what the problem is... You're having discrepancies but you don't know from where. It could be in your computation (and I think I already found one), or in that of surprise. But I feel like you're asking me to debug both, and I simply cannot do that.

There's already an issue for pearson similarity in #224. If there's an issue somewhere else, e.g. in `KNNWithMeans`, please **isolate** it.

About xlsx: I meant I can't open xlsx files at all. I don't have excel basically (nor any alternative), and don't want to.

**Comment by TamTSE2301** [comment] 2018-11-15 00:05
Hi again. My apology for any inconvenience so far. I have uploaded the source file (csv format) in my github: https://github.com/TamTSE2301/Recommendation-system/blob/master/data.csv

Let's check the Pearson sim of U1 vs the rest here. Compared to Surprise library, I got different values for the case from U4 to U10.

> It looks like you're not computing the pearson similarity on the common ratings only, so you're definitely get different results
In my code, there is a creation of indexList which is the list of common ratings.
`indexList = (v1[(~pd.isnull(v1)) & (~pd.isnull(v2))]).index 
` 
This is my result:
![capture](https://user-images.githubusercontent.com/40611425/48520618-97c4b680-e871-11e8-8aeb-a0c587b73a11.JPG)

This is Suprise result (I use your KNNWithMeans)
![capture2](https://user-images.githubusercontent.com/40611425/48520658-b4f98500-e871-11e8-8397-b14142f25eab.JPG)

You could see my code here: https://github.com/TamTSE2301/Recommendation-system/blob/master/Surprise%20Library%20Check%20-%20Similarity%20matrix.py

This is the file I calculate by hand in Excel: https://github.com/TamTSE2301/Recommendation-system/blob/master/ManualComputation.xlsx
It has the same result with my code

> There's already an issue for pearson similarity in #224.
I checked that issue. From what I understand it is about the two versions of Pearson formulas in Wiki. I don't think it is the cause here since when I calculate by hand the case of U1 and U6 by both formulas, they deliver the result: -0.57124 while it is 0 in Surprise. 
--

**Comment by NicolasHug** [comment] 2018-11-15 03:37
Sorry but once again, this is really far from a minimal reproducible example. Please read the link above.

A lot of the values from the 2 screenshot look the same. Please be aware that the indices in `sim` are inner indices, not raw indices (check out the FAQ). That might explain a lot of the discrepancies.

> I don't think it is the cause here since when I calculate by hand the case of U1 and U6 by both formulas, they deliver the result: -0.57124 while it is 0 in Surprise.

This is precisely what #224 is about.

**Comment by NicolasHug** [comment] 2018-12-09 16:14
@TamTSE2301 can I close this issue?

**Comment by TamTSE2301** [comment] 2018-12-09 16:15
Hi. Sorry for my late response. The problem is solved. It is due to the inner indices. Thanks for your help.

**Closed** 2018-12-09 17:19 UTC
