### ISSUE TITLE
Not being able to predict ratings for already seen users and items

### ISSUE THREAD

**Issue by apalmk** [NicolasHug/Surprise#312] opened 2019-11-02 09:01 UTC
#### Description

I have my manual training and testing sets in pandas dataframes, I converted them to your dataset format. I haven't used "build full train set" as I am not training on the entire data.

When I am doing this
`ppv_trainset.knows_user(62)`
It is returning TRUE
When I am doing this 
`ppv_trainset.knows_item(170)`
It is returning TRUE

But when I am doing this
`Knnobject.predict(62,170)`

Its returning
"was_impossible': True, 'reason': 'User and/or item is unkown'"
#### Steps/Code to Reproduce

```
split = math.floor(final_df.timestamp.quantile(q=.8))
train_set_ppv = final_df[final_df['timestamp']<split]
test_set = final_df[final_df['timestamp']>=split]

fin=final_df[['userId', 'movieId', 'ppv']].copy()
train_set_ppv1=train_set_ppv[['userId', 'movieId', 'ppv']].copy()

reader = Reader(rating_scale=(min_ppv, max_ppv))
//fin is the entire dataframe haveing both train and test sets
data=Dataset.load_from_df(fin,reader)
ppv_train_data = Dataset.load_from_df(train_set_ppv1, reader)
ppv_trainset = data.construct_trainset(ppv_train_data.raw_ratings)
```

#### Expected Results
the predicted rating
#### Versions

Linux-4.14.137+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
surprise 1.1.0

**Comment by NicolasHug** [comment] 2019-11-02 15:09
Have you double checked https://surprise.readthedocs.io/en/stable/FAQ.html#what-are-raw-and-inner-ids ?

**Comment by apalmk** [comment] 2019-11-02 16:18
I have checked it, is there anything wrong with how I am taking in the train and test data, using construct train and test sets? It says it knows the user and it knows the item but it is not able to predict their ratings.

**Comment by NicolasHug** [comment] 2019-11-02 16:34
predict accepts raw ids
knows_blahblah accept inner ids

You need to pass raw ids to predict i.e. what they are in your input dataframes. They might be strings.

**Comment by apalmk** [comment] 2019-11-02 16:40
Even when I am not manually checking predict for each row, and using test functions like the below
```
data=Dataset.load_from_df(fin,reader)
test_set_data = Dataset.load_from_df(test_set1, reader)
test_set_1=data.construct_testset(test_set_data.raw_ratings)
predictions1 = Knnobject.test(test_set_1)
```
and then I am checking the outputs, I am getting a lot of these user/item unknown issues.

**Comment by apalmk** [comment] 2019-11-02 16:42
Which is why I was asking if my method of taking maual train and test sets from dataframes is the right way of doing it? Cuz I checked the documentation and the only way they took in manual test and train sets was through load folds from csv files. How can we do it using dataframes?

**Comment by NicolasHug** [comment] 2019-11-02 16:55
If you're seeing " "was_impossible': True, 'reason': 'User and/or item is unkown'""

That means the user or the item you're passing isn't present in the training set.

There's a 99% chance it's caused by a discrepancy between raw and inner ids.

> the only way they took in manual test and train sets was through load folds from csv files. 

No, you can just load a dataset and use build_full_trainset and then call `predict` on the elements of your testset.

**Comment by NicolasHug** [comment] 2019-11-02 16:56
I can't help you more than that unless you give me a reproducible and minimal example.

**Comment by apalmk** [comment] 2019-11-02 17:03
"No, you can just load a dataset and use build_full_trainset and then call predict on the elements of your testset."

How do I construct my testset? Is it like this?

```
data=Dataset.load_from_df(fin,reader)
test_set_data = Dataset.load_from_df(test_set1, reader)
test_set_1=data.construct_testset(test_set_data.raw_ratings)
predictions1 = Knnobject.test(test_set_1)

```

**Comment by NicolasHug** [comment] 2019-11-02 17:26
there is no data structure  for the testset. Just use `predict`.

**Comment by apalmk** [comment] 2019-11-02 17:37
For using `predict` I will have to send each user item pair in my data frame as parameter right? Or can I send the entire data frame as `Knnobject.predict(test_dataframe)` ?

**Comment by NicolasHug** [comment] 2019-11-03 18:57
> For using predict I will have to send each user item pair in my data frame as parameter right? 

Yes

**Comment by NicolasHug** [comment] 2019-11-16 14:39
Can I close this issue?

**Closed** 2019-11-19 18:18 UTC
