### ISSUE TITLE
Unable to use RandomizedSearchCV consecutively 

### ISSUE THREAD

**Issue by rthothad** [NicolasHug/Surprise#241] opened 2019-01-12 05:57 UTC
#### Description
When I try to run RandomizedSearchCV consecutively I get the below error. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-37-62bda5b23989> in <module>()
      8                               'user_based': [False]}
      9               }
---> 10 rs = RandomizedSearchCV(KNNBaseline, params, measures=['rmse'], cv=3)
     11 rs.fit(train_data)
     12 

d:\Tools\Miniconda3\envs\py_3_6_5_keras\lib\site-packages\surprise\model_selection\search.py in __init__(self, algo_class, param_distributions, n_iter, measures, cv, refit, return_train_measures, n_jobs, pre_dispatch, random_state, joblib_verbose)
    426             param_distributions.copy())
    427         self.param_combinations = self._sample_parameters(
--> 428             self.param_distributions, self.n_iter, self.random_state)
    429 
    430     @staticmethod

d:\Tools\Miniconda3\envs\py_3_6_5_keras\lib\site-packages\surprise\model_selection\search.py in _sample_parameters(param_distributions, n_iter, random_state)
    478             param_grid = [dict(zip(param_distributions, v)) for v in
    479                           product(*param_distributions.values())]
--> 480             combos = np.random.choice(param_grid, n_iter, replace=False)
    481 
    482         else:

mtrand.pyx in mtrand.RandomState.choice()

ValueError: Cannot take a larger sample than population when 'replace=False'

**Comment by NicolasHug** [comment] 2019-01-12 14:09
Please provide [self-contained example code](https://stackoverflow.com/help/mcve), including imports and data (if possible), so that other contributors can just run it and reproduce your issue. Ideally your example code should be minimal.

**Comment by sa1as** [comment] 2019-01-23 14:54
The reason for this error comes from np.RandomizedSearchCV() which by default has n_iter = 10, and the same is for surprise. So if the parameter combination you are using is below that then it will create an error. Try defining manually changing that as a parameter top RandomizedSearchCV() or giving a combination  > 10.

**Comment by NicolasHug** [comment] 2019-01-23 15:07
It looks like @rthothad set `cv=3`. But I agree with you that it likely comes from a mismatch between the number of folds and the size of the data.

Anyway, no feedback for days, I'm closing the issue. Thanks for the help @sa1as .

**Closed by NicolasHug** 2019-01-23 15:07 UTC
